services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amc-carpool-data
    container_name: amc_carpool_data
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
