services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: amc-carpool-api-production
    container_name: amc_carpool_api_production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
