services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amc-carpool-api
    container_name: amc_carpool_api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development

  local_db:
    image: postgres:latest
    container_name: local_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: localdb
      POSTGRES_PASSWORD: localdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
