# Use the official Node.js image as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy all the necessary files to run on production
COPY package*.json ./
COPY node_modules ./node_modules
COPY dist ./dist

# Since we're running in production, just use regular `node`
CMD ["sh", "-c", "node dist/server.js" ]
